/**:
  ros__parameters:
    enable_lstm_smoothing: false
    lstm_smoothing_model: "v11.onnx"

    ### Subscribe topics
    camera_info_topic: "autoaim/camera/camera_info"
    selected_detections_topic: "autoaim/selector/detections"

    ### Publish topics
    poses_topic: "autoaim/locator/poses"