%YAML:1.0
---

# 均采用国际单位制，距离为m，时间为s，角度为弧度

armor_tracker:
  approximate_framerate: 100
  err_queue_size: 80
  low_accuracy_err_threshold: 0.1
  
  kf_main_observing_armor:
    process_noise: !!opencv-matrix
      rows: 6
      cols: 6
      dt: f
      data: [ 1e-0,  0,  0,  0,  0,  0,
              0,  1e-0,  0,  0,  0,  0,
              0,  0,  1e-0,  0,  0,  0,
              0,  0,  0,  5e+1,  0,  0,
              0,  0,  0,  0,  5e+1,  0,
              0,  0,  0,  0,  0,  5e+1 ]
    measurement_noise: !!opencv-matrix
      rows: 3
      cols: 3
      dt: f
      data: [ 1e-1,  0,  0,
              0,  1e-1,  0,
              0,  0,  1e-1 ]

  car_status:
    max_temp_lost_frames: 10
    max_converging_frames: 10

  outpost_status:
    max_temp_lost_frames: 30
    max_converging_frames: 15

  car_observer:
    initial_radius: 0.26
    switch_armor_angle: 1.0
    delta_yaw_update_threshold: 0.3
    enter_antispin_palstance: 2.5
    exit_antispin_palstance: 1.0
    antispin_shoot_angle: 0.35
    antispin_out_of_shoot_angle_threshold: 4
    antispin_in_shoot_angle_threshold: 4
    radius_filter_ratio: 0.95
    height_filter_ratio: 0.95
    axis_filter_ratio: 0.9
    kf_center:
      process_noise: !!opencv-matrix
        rows: 6
        cols: 6
        dt: f
        data: [ 1e-0,  0,  0,  0,  0,  0,
                0,  1e-0,  0,  0,  0,  0,
                0,  0,  1e-0,  0,  0,  0,
                0,  0,  0,  1e+1,  0,  0,
                0,  0,  0,  0,  1e+1,  0,
                0,  0,  0,  0,  0,  1e+1 ]
      measurement_noise: !!opencv-matrix
        rows: 3
        cols: 3
        dt: f
        data: [ 1e+1,  0,  0,
                0,  1e+1,  0,
                0,  0,  1e+1 ]
    kf_yaw:
      process_noise: !!opencv-matrix
        rows: 2
        cols: 2
        dt: f
        data: [ 1e-0,  0, 
                0,  1e+1 ]
      measurement_noise: !!opencv-matrix
        rows: 1
        cols: 1
        dt: f
        data: [ 1e-1 ]

  outpost_observer:
    radius: 0.273
    switch_armor_angle: 1.0
    delta_yaw_update_threshold: 0.2
    outpost_shoot_angle: 0.6
    outpost_out_of_shoot_angle_threshold: 5
    outpost_in_shoot_angle_threshold: 5
    kf_center:
      process_noise: !!opencv-matrix
        rows: 6
        cols: 6
        dt: f
        data: [ 1e-1,  0,  0,  0,  0,  0,
                0,  1e-1,  0,  0,  0,  0,
                0,  0,  1e-1,  0,  0,  0,
                0,  0,  0,  5e-1,  0,  0,
                0,  0,  0,  0,  5e-1,  0,
                0,  0,  0,  0,  0,  5e-1 ]
      measurement_noise: !!opencv-matrix
        rows: 3
        cols: 3
        dt: f
        data: [ 1e+1,  0,  0,
                0,  1e+1,  0,
                0,  0,  1e+1 ]
    kf_yaw:
      process_noise: !!opencv-matrix
        rows: 2
        cols: 2
        dt: f
        data: [ 1e-1,  0, 
                0,  1e-0 ]
      measurement_noise: !!opencv-matrix
        rows: 1
        cols: 1
        dt: f
        data: [ 1e-1 ]