%YAML:1.0
---

# 均采用国际单位制，距离为m，时间为s，角度为rad

buff_tracker:
  small_buff_status:
    max_temp_lost_frames: 20
    max_converging_frames: 20
  
  small_buff_observer:
    queue_size: 20
    queue_sample_interval: 5
    small_buff_speed: 1.047197551 # 60deg/s
    R_center_filter_ratio: 0.3