%YAML:1.0
---

# 均采用国际单位制，距离为m，时间为s，角度为弧度

Car:
  initial_radius: 0.26
  switch_armor_angle: 0.7
  radius_filter_ratio: 0.7
  height_filter_ratio: 0.7
  axis_filter_ratio: 0.7
  kf_center:
    process_noise: !!opencv-matrix
      rows: 6
      cols: 6
      dt: f
      data: [ 1e-0,  0,  0,  0,  0,  0,
              0,  1e-0,  0,  0,  0,  0,
              0,  0,  1e-0,  0,  0,  0,
              0,  0,  0,  1e-0,  0,  0,
              0,  0,  0,  0,  1e-0,  0,
              0,  0,  0,  0,  0,  1e-0 ]
    measurement_noise: !!opencv-matrix
      rows: 3
      cols: 3
      dt: f
      data: [ 3e-3,  0,  0,
              0,  3e-3,  0,
              0,  0,  1e-1 ]
  
  kf_yaw:
    process_noise: !!opencv-matrix
      rows: 2
      cols: 2
      dt: f
      data: [ 5e-4,  0, 
              0,  1e-2 ]
    measurement_noise: !!opencv-matrix
      rows: 1
      cols: 1
      dt: f
      data: [ 1e-3 ]

Status:
  max_temp_lost_frames: 10
  max_converging_frames: 10

CarTracker:
  enter_antispin_palstance: 3.0
  exit_antispin_palstance: 1.8
  antispin_follow_angle: 0.55
  antispin_shoot_angle: 0.5
  kf_main_observing_armor:
    process_noise: !!opencv-matrix
      rows: 6
      cols: 6
      dt: f
      data: [ 1e-0,  0,  0,  0,  0,  0,
              0,  1e-0,  0,  0,  0,  0,
              0,  0,  1e-1,  0,  0,  0,
              0,  0,  0,  1e+2,  0,  0,
              0,  0,  0,  0,  1e+2,  0,
              0,  0,  0,  0,  0,  1e-0 ]
    measurement_noise: !!opencv-matrix
      rows: 3
      cols: 3
      dt: f
      data: [ 3e-5,  0,  0,
              0,  3e-5,  0,
              0,  0,  1e-2 ]