/**:
  ros__parameters:
    enable_anti_dart: true
    enable_detected_image: false

    image_topic: "autoaim/camera/image_raw"
    camera_info_topic: "autoaim/camera/camera_info"
    bullet_speed_sub_topic: "serial/bullet_speed"

    shoot_pos_pub_topic: "autoaim/shoot_pos"
    image_detected_topic: "autoaim/dart_detected_image"

    # 默认的弹速。收到串口节点发送的消息后会被覆盖
    bullet_speed: 24.0 # 单位: m/s

    target_to_light_z: 0.08 # 飞镖靶到引导灯的高度

    shoot_compensate_pitch: -1.0 # 单位: deg
    shoot_compensate_yaw: -1.2 # 单位: deg