%YAML:1.0
---

dt: 0.01 # 单位时间

StandardEKF:
  init_radius: 0.25 # 初始半径
  gain: 15 # 测距噪声关于角度的增益倍数

  # 状态转移噪声系数
  process_noise:
    displace_high_diff: 3
    anglar_high_diff: 15
    height: 0.0001
    radius: 0.000005

  # 观测噪声系数
  measure_noise:
    pose: 0.002
    distance: 0.1
    angle: 0.5

StandardEKFTracker:
  switch_threshold: 15 # 更新装甲板切换的角度阈值，角度制。
  match_score_threshold: 1.0 # get_match中最大允许的score。