/**:
  ros__parameters:
    enable_print_state: false
    enable_send_to_serial: false

    # 默认的目标敌人优先级序列。收到决策发送的消息后会被覆盖
    enemy_priority: [0, 1, 2, 3, 4, 5]

    # 默认的目标敌人颜色和弹速。收到串口节点发送的消息后会被覆盖
    target_color: 0 # 0: blue, 1: red
    bullet_speed: 24.0 # 单位: m/s

    control_to_fire_time: 0.04 # 单位: s
    shoot_compensate_pitch: -1.0 # 单位: deg
    shoot_compensate_yaw: -1.2 # 单位: deg

    camera_info_topic: "autoaim/camera/camera_info"
    detection_sub_topic: "autoaim/detection"
    robot_color_sub_topic: "serial/robot_color" # 根据自己的颜色判断击打目标颜色
    bullet_speed_sub_topic: "serial/bullet_speed"
    robots_hp_topic: "serial/comp_robots_hp" # 从串口节点接收，获取敌方机器人血量筛掉死人和无敌人
    enemy_priority_sub_topic: "decision/enemy_priority" # 从决策接收，指定打人的优先级

    shoot_pos_pub_topic: "autoaim/shoot_pos"
    debug_info_pub_topic: "autoaim/debug_info"