autoaim_detection:
  ros__parameters:
    image_topic: "/camera/color/image_raw"
    detection_topic: "/detection"
    image_detected_topic: "/debug/detected_image"

    onnx_name: "20250226.onnx"
    confidence_threshold: 0.4
    nms_threshold: 0.4

    enable_detected_image: true
    enable_fps: false