/**:
  ros__parameters:
    image_topic: "autoaim/camera/image_raw"
    detection_topic: "autoaim/detection"
    image_detected_topic: "autoaim/detected_image"

    model_path: "20250503v11.xml"
    confidence_threshold: 0.4
    nms_threshold: 0.4

    enable_detected_image: true
    enable_fps: false